Can not access ftp.mcs.anl.gov
Use local copy of the file as ftp.mcs.anl.gov can not be accessed due to
certificate issue:
```
Resolving ftp.mcs.anl.gov (ftp.mcs.anl.gov)... 172.65.90.25, 172.65.90.24, 172.65.90.27, ...
Connecting to ftp.mcs.anl.gov (ftp.mcs.anl.gov)|172.65.90.25|:443... connected.
ERROR: The certificate of ‘ftp.mcs.anl.gov’ is not trusted.
ERROR: The certificate of ‘ftp.mcs.anl.gov’ doesn't have a known issuer.
```

Signed-off-by: Tomasz Gromadzki <tomasz.gromadzki@hpe.com>